### ISSUE TITLE
找不到这个目录model/trained_model_1.h5

### ISSUE THREAD

**Issue by zhouyanping123** [Meituan-Dianping/vision#1]
![image](https://user-images.githubusercontent.com/36906522/61850288-85ae1400-aee6-11e9-92c2-6a67b3a4c5ef.png)

**Comment by BrightHai** [comment]
训练后的模型保存路径问题，可以先在工程目录下创建model文件夹

**Comment by zhouyanping123** [comment]
![image](https://user-images.githubusercontent.com/36906522/61852022-053de200-aeeb-11e9-908f-ab062102cdb1.png)
运行rcnn_train.py文件训练？出来的是train文件夹下面一堆png，不明白怎么变成“model/trained_model_1.h5”

**Comment by BrightHai** [comment]
train目录是根据训练集自动生成的增强训练集，model目录是用来存储训练后生成的模型，之前的报错是因为没有model这个目录，然后保存模型的时候出错，稍后会修复这个问题

**Comment by zhouyanping123** [comment]
跑出来了，感谢解答
