### ISSUE TITLE
这张图片返回的xy位置不对，按目前的返回的是（546,639），实际位置（619,403），我自己加了图片进去训练，出来的还是不对，求教，需要截那两张图片

### ISSUE THREAD

**Issue by zhouyanping123** [Meituan-Dianping/vision#3]
![image](https://user-images.githubusercontent.com/36906522/61924574-029ac580-af9b-11e9-92aa-f7e980d97c85.png)

**Comment by BrightHai** [comment]
最新版加入了这张图的训练数据，增加自己的训练数据可以把目标截图命名为1_x.png背景截图命名为0_x.png放在image目录下
